# Generated by Django 3.2 on 2023-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpq', '0003_alter_job_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
